### numpy使用
> 使用numpy相关函数

In [1]:
import numpy as np
data = [1,2,3,4]
data.append(4)
print(data)
arr = np.array(data)
print(arr.shape)
print(np.zeros((2,8)))
print(np.empty((2,3,3)))
print(arr[0:-1])
print(arr[-3:-1])
print(arr[:2])
print(arr.mean())
print(arr.sum(0))
rnd_arr = np.random.randn(7,4)
print(rnd_arr.mean())


[1, 2, 3, 4, 4]
(5,)
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[[4.64109699e-310 4.64109709e-310 3.95252517e-322]
  [3.16202013e-322 4.64109710e-310 6.94958600e-310]
  [6.94958600e-310 6.94958600e-310 6.94958600e-310]]

 [[6.94958600e-310 6.94958600e-310 6.37344683e-322]
  [6.94959059e-310 4.64109709e-310 6.94958600e-310]
  [6.94958600e-310 6.94958690e-310 6.94958600e-310]]]
[1 2 3 4]
[3 4]
[1 2]
2.8
14
0.10223519817111255


In [2]:
name_arr = np.array(['bob','will','joe','bob','will','joe','bob'])
rnd_arr = np.random.randn(7,4)
print(rnd_arr)
print(-(rnd_arr[name_arr == 'bob']))
print(rnd_arr[name_arr == 'bob',:2])

[[-2.61871998  0.34818375  1.32337071  0.47494274]
 [ 0.9509322  -0.18798561  0.20021169 -0.0631376 ]
 [-0.75778114 -0.84102186 -0.02562566 -1.05013998]
 [ 1.18134638 -0.54374316 -1.60184538  0.59348285]
 [-0.99625402 -0.0641303  -0.3512148   0.71407034]
 [ 0.05850932 -0.08845026 -0.38062437  0.56017061]
 [ 0.30315394  0.76724306  0.96899404 -0.10590187]]
[[ 2.61871998 -0.34818375 -1.32337071 -0.47494274]
 [-1.18134638  0.54374316  1.60184538 -0.59348285]
 [-0.30315394 -0.76724306 -0.96899404  0.10590187]]
[[-2.61871998  0.34818375]
 [ 1.18134638 -0.54374316]
 [ 0.30315394  0.76724306]]
