### numpy使用
> 使用numpy相关函数

In [53]:
import numpy as np
data = [1,2,3,4]
data.append(4)
print(data)
arr = np.array(data)
print(arr.shape)
print(np.zeros((2,8)))
print(np.empty((2,3,3)))
print(arr[0:-1])
print(arr[-3:-1])
print(arr[:2])
print(arr.mean())
print(arr.sum(0))
rnd_arr = np.random.randn(7,4)
print(rnd_arr.mean())


[1, 2, 3, 4, 4]
(5,)
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[[-0.00000000e+000  2.68678506e+154  4.44659081e-323]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  4.94065646e-324  2.12199579e-314]]

 [[ 0.00000000e+000  2.12199579e-314  2.18570311e-314]
  [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
  [ 2.18570311e-314  2.18570311e-314  1.25160405e-308]]]
[1 2 3 4]
[3 4]
[1 2]
2.8
14
0.10393071605716499


In [43]:
name_arr = np.array(['bob','will','joe','bob','will','joe','bob'])
rnd_arr = np.random.randn(7,4)
print(rnd_arr)
print(-(rnd_arr[name_arr == 'bob']))
print(rnd_arr[name_arr == 'bob',:2])

[[-1.41104963 -1.4663973  -0.21878198  0.29088529]
 [-1.30382217  0.2655209  -0.07837415 -1.21473108]
 [-1.78414805  0.42763596 -0.02951698  0.8961963 ]
 [ 1.20081597  0.85000954  1.07181053  0.06691148]
 [-0.01344792  1.21659777 -1.16704537 -0.97813761]
 [-0.28346981  0.80046104 -0.04405093 -0.04600195]
 [-0.49633215 -0.74552287  0.37010187  2.68435613]]
[[ 1.41104963  1.4663973   0.21878198 -0.29088529]
 [-1.20081597 -0.85000954 -1.07181053 -0.06691148]
 [ 0.49633215  0.74552287 -0.37010187 -2.68435613]]
[[-1.41104963 -1.4663973 ]
 [ 1.20081597  0.85000954]
 [-0.49633215 -0.74552287]]
